apiVersion: apps/v1
kind: Deployment
meta:
  name: nginx
  lables:
    app: nginx
spec:
 replicas: 10
 templates:
   metadata: 
     labels:
       app: nginx
 spec:
   containers:
    - name: nginx
     #image: ${REGISTRY_URL}nodejs-test:latest
     image: nginx:1.14.2
     imagePullPolicy: Always
     ports:
        - containerPort: 80
 #     imagePullPolicy: Always

  

    # ports:
    #   - containerPort: 3000
    #     protocol: TCP
    #     initialDelaySeconds: 10
    #     timeoutSeconds: 10
    #     periodSeconds: 10
    #     successThreshold: 1
    #     failureThreshold: 5

     resources:
        requests:
          cpu: 1
          memory: "2Gi"
        limits:
          cpu: 1
          memory: "2Gi"

