apiVersion: apps/v1
kind: Deployment
metadata:
   name: nodejs-dev
   labels:
     app: nodejs-dev
spec:
 replicas: 2
 selector:
   matchLabels:
        app: nodejs-dev
 template:
   metadata:
     labels:
       app: nodejs-dev
   spec:
     containers:
     - name: nodejs-test
       image: 102315585312.dkr.ecr.us-east-2.amazonaws.com/nodejs-test
